### ISSUE TITLE
Integrate Twitter Bootstrap into Rails (1)

### ISSUE THREAD

**Issue by hessnd** [hessnd/tc359_rails_final#4]
Added Bootstrap @chrisvfritz

**Comment by chrisvfritz** [comment]
Same comment here about deleting [the bootstrap folder](https://github.com/hessnd/tc359_rails_final/tree/master/app/assets/stylesheets/bootstrap). And I also don't see the 3+ Bootstrap variables being overridden.

**Comment by hessnd** [comment]
What bootstrap variables?

**Comment by hessnd** [comment]
I also wanted to ask you if you think that on my landing page area if I need to have the icon showing the action to scroll down?

**Comment by chrisvfritz** [comment]
You'd override any of [these variables](http://getbootstrap.com/customize/#less-variables) by defining them before including Bootstrap's styles. You can [see an example here](https://github.com/chrisvfritz/codekwondo/blob/master/app/assets/stylesheets/bootstrap/variables.scss).

I personally like that icon showing to scroll down. One thing I noticed though is that the text and the arrow didn't have a lot of contrast with background. There are a few tricks you could use to fix this:

One would be to add a little `text-shadow` to the text. For example:

``` css
text-shadow: -1px 1px 0 black;
```

And you could also add a dark, semi-transparent overlay to the background. You could achieve this with something like:

``` scss
.landing > .container {
  position: relative;

  &:after {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.6);
    z-index: 1;
  }

  h1, p {
    position: relative;
    z-index: 2
  }
}
```

Let me know what you think. :smiley:
